name: Android

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Release
        run: |
          cd android && ./gradlew bundleRelease -ANDROID_KEYSTORE_PASSWORD='${{ secrets.ANDROID_KEYSTORE_PASSWORD }}' -ANDROID_KEYSTORE_ALIAS='upload' -ANDROID_KEY_PASSWORD='${{ secrets.ANDROID_KEY_PASSWORD }}'
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app.aab
          path: android/app/build/outputs/bundle/release/
