name: iOS

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-android:
    name: iOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Install CocoaPods
        run: cd ios && pod install && cd ..
      - name: Build app
        run: |
          cd ios && xcodebuild archive \
            -workspace NewsApp.xcworkspace \
            -scheme NewsApp \
            -configuration Release \
            -archivePath $PWD/build/NewsApp.xcarchive \
            IPHONEOS_DEPLOYMENT_TARGET=9.0
      - name: Export app
        run: |
          cd ios && xcodebuild \
            -exportArchive \
            -archivePath $PWD/build/NewsApp.xcarchive \
            -exportPath $PWD/build
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: NewsApp.ipa
          path: ios/build
